name: Notify Single User

on:
  workflow_dispatch: # manual trigger

jobs:
  notify_user:
    runs-on: ubuntu-latest

    steps:
      - name: Send Notification to hamburg02
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/issues \
            -d "{\"title\":\"📢 Personal GitHub Notification\",\"body\":\"Hello @hamburg02! This is a direct GitHub notif
