name: GitHub Message Sender (No CLI)

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: "0 9 * * *" # optional: daily at 9 AM UTC

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Send GitHub Message via REST API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/issues \
            -d '{"title":"🚀 Your Daily GitHub Message","body":"Hello! This is a GitHub-generated message. All watchers of this repo will get a notification automatically."}'
